USE [D:\C#\LIBRARYAPP\LIBRARYDAL\LIBDATABASE.MDF] --create db and change link
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BookName] [nvarchar](150) NOT NULL,
	[Authors] [nvarchar](150) NOT NULL,
	[YearOfPublishing] [int] NOT NULL,
 CONSTRAINT [PK__Books__3214EC2708455360] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](24) NOT NULL,
	[PassHash] [varchar](32) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[DateOfBirth] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE Users ADD CONSTRAINT U_Username UNIQUE(Username)

CREATE APPLICATION ROLE lib_app WITH PASSWORD = 'DFa[7wzaVA'

DENY BACKUP DATABASE, BACKUP LOG, CREATE PROCEDURE, CREATE TABLE TO lib_app CASCADE
GRANT Insert, Select, Update, Delete ON Books TO lib_app
GRANT Insert, Select, Update, Delete ON Users TO lib_app